# Python Lab

## Basic Arithmetic Operations
This cell demonstrates basic addition of two integers.

## Integer Interning in Python

Python uses **integer interning** (also called **integer caching**) as a memory optimization technique. For small integers in the range of -5 to 256, Python pre-creates and reuses the same integer objects rather than creating new ones each time.

This means when you assign the same small integer value to different variables, they actually reference the same object in memory, which is why `id(a)` and `id(b)` return identical memory addresses.

This optimization:

- Reduces memory usage
- Improves performance for frequently used small integers
- Is completely transparent to the programmer

In [33]:
a = 5
b = 3
print(a + b)

8


In [34]:
a = 5
b = 5
print(id(a), id(b))

4341137776 4341137776


## List Identity vs Equality

This cell demonstrates the difference between identity (`is`) and equality (`==`) with lists. Unlike small integers, lists are **not** interned in Python. Even when two lists have identical contents, they are separate objects in memory with different `id()` values. The `==` operator checks if values are equal, while `is` checks if they are the same object.

In [35]:
a = [1, 2, 3]
b = [1, 2, 3]
print(id(a), id(b))
print(a == b)
print(a is b)

4470112192 4469162112
True
False


## Mutable Objects in Python

Lists are **mutable objects**, meaning their contents can be modified after creation without changing their identity (memory address). This cell demonstrates how using `append()` modifies the list in-place - the `id()` remains the same before and after modification, proving it's the same object with changed contents.

In [36]:
b = [1, 2, 3]
print("Before append:")
print("b =", b)
print("id(b) =", id(b))

b.append(4)
print("\nAfter append:")
print("b =", b)
print("id(b) =", id(b))

Before append:
b = [1, 2, 3]
id(b) = 4563591808

After append:
b = [1, 2, 3, 4]
id(b) = 4563591808


## Copying Lists

This cell demonstrates different ways to create copies of lists in Python.

In [37]:
# Cách 1: Dùng slicing
a = [1, 2, 3]
b = a[:]   # tạo bản sao nông (shallow copy)
b.append(4)
print(a, b)

# Cách 2: Dùng list()
a = [1, 2, 3]
b = list(a)
b.append(4)
print(a, b)

# Cách 3: Dùng thư viện copy
import copy
a = [1, 2, [10, 20]]
b = copy.deepcopy(a)  # tạo bản sao sâu (deep copy)
b[2].append(30)
print(a, b)

[1, 2, 3] [1, 2, 3, 4]
[1, 2, 3] [1, 2, 3, 4]
[1, 2, [10, 20]] [1, 2, [10, 20, 30]]


## Visualizing the Difference: Shallow vs Deep Copy

This example clearly demonstrates the behavior difference between `copy.copy()` (shallow) and `copy.deepcopy()` (deep):

- **Variable `a`**: Original list with a nested list `[2, 3]`
- **Variable `b`**: Shallow copy - creates a new outer list, but shares the nested list with `a`
  - When we do `b[1].append(4)`, it modifies the shared nested list
  - Both `a` and `b` show `[2, 3, 4]` because they point to the same nested list object
- **Variable `c`**: Deep copy - creates completely independent copies at all levels
  - When we do `c[1].append(5)`, it only modifies `c`'s own nested list
  - `a` and `b` are unaffected

**Result**: This proves shallow copy shares nested objects while deep copy creates truly independent copies.

In [38]:
import copy

a = [1, [2, 3]]
b = copy.copy(a)      # shallow copy
c = copy.deepcopy(a)  # deep copy

b[1].append(4)
c[1].append(5)

print("a:", a)
print("b:", b)
print("c:", c)

a: [1, [2, 3, 4]]
b: [1, [2, 3, 4]]
c: [1, [2, 3, 5]]


# Data Structures in Python - Lists

Python's **list** is one of the most versatile data structures. Lists are:

- **Ordered**: Elements maintain their position
- **Mutable**: Can be modified after creation
- **Dynamic**: Can grow or shrink in size
- **Heterogeneous**: Can contain different data types

This cell demonstrates fundamental list operations: indexing to access elements and `append()` to add elements.

In [39]:
nums = [10, 20, 30]
print(nums[0])
nums.append(40)
print(nums)

10
[10, 20, 30, 40]


List can have different data type elements

In [40]:
nums = [10, "AI", [1, 2, 3], True]

In [41]:
nums = [1, 2, 3, 4]
for x in nums:
    print(x * 2)

2
4
6
8


Another **list comprehension**

In [42]:
nums = [1, 2, 3, 4]
doubles = [x * 2 for x in nums]
print(doubles)

[2, 4, 6, 8]


In [43]:
matrix = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

flattened = [x for row in matrix for x in row]
print(flattened)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


Create an array *nums* contains element from 1 to 10. And create another array *squares* based on *num* with square operator if element is even:

In [44]:
nums = list(range(1,10))
squares = [n**2 for n in nums if n % 2 == 0]
print(squares)

[4, 16, 36, 64]


## Note: The `range()` Function and Lazy Evaluation

The `range()` function creates an **iterable** that generates numbers on-demand using **lazy evaluation**:

- **Lazy Evaluation**: Values are generated only when needed, not all at once
- **Memory Efficient**: `range(1000000)` doesn't create a list of 1 million numbers in memory
- **Iterable**: Can be used in loops, converted to lists with `list()`, or consumed by other functions
- **Immutable**: The range object itself cannot be modified

Example: `range(1, 10)` creates an iterable that will produce numbers 1 through 9 when iterated over, but the numbers aren't generated until you actually use them (like in a loop or when converting to a list with `list(range(1, 10))`).

This is a key performance optimization in Python, especially when working with large sequences.

# NumPy

## Introduction to NumPy Arrays

**NumPy** (Numerical Python) is a fundamental library for scientific computing in Python. This cell demonstrates creating a NumPy array using `np.array()`:

- NumPy arrays are more efficient than Python lists for numerical operations
- The type `numpy.ndarray` (n-dimensional array) is the core data structure
- Arrays are homogeneous - all elements must be the same type
- Ideal for mathematical and scientific computations

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


## Vectorized Operations in NumPy

This demonstrates **vectorization** - one of NumPy's most powerful features:

- Operations are applied to entire arrays at once, not element-by-element
- `arr + 10` adds 10 to every element without needing a loop
- Much faster than iterating through Python lists
- Makes code cleaner and more readable
- NumPy operations are implemented in C, providing significant performance gains

In [46]:
arr = np.array([1, 2, 3, 4, 5])
print(arr + 10)

[11 12 13 14 15]


In [47]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)
print(a * b)
print(np.dot(a, b))

[5 7 9]
[ 4 10 18]
32


## Matrix Multiplication: `@` Operator vs Element-wise Operations

This cell demonstrates the `@` operator for **matrix multiplication**, which is fundamentally different from element-wise operations:

### The `@` Operator - Matrix Multiplication
- Performs **linear algebra matrix multiplication** (dot product)
- Each element in the result is the sum of products of corresponding row and column elements
- Formula: `(A @ B)[i,j] = sum of (A[i,k] * B[k,j])` for all k
- **Calculation example from this cell**:
  - `Result[0,0] = (1×5) + (2×7) = 5 + 14 = 19`
  - `Result[0,1] = (1×6) + (2×8) = 6 + 16 = 22`
  - `Result[1,0] = (3×5) + (4×7) = 15 + 28 = 43`
  - `Result[1,1] = (3×6) + (4×8) = 18 + 32 = 50`

### Element-wise Operations (`*`, `+`, `-`, `/`)
- `A * B` multiplies corresponding elements: `Result[i,j] = A[i,j] * B[i,j]`
- Example: `[[1,2],[3,4]] * [[5,6],[7,8]] = [[1*5, 2*6],[3*7, 4*8]] = [[5,12],[21,32]]`
- Simple position-by-position operation, no cross-element computation

**Key Difference**: `@` combines multiple elements (row × column), while `*` operates on single pairs of elements.

In [48]:
A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

print(A @ B)


[[19 22]
 [43 50]]


## NumPy Broadcasting Rules

**Broadcasting** is NumPy's powerful mechanism for performing operations on arrays of different shapes. Instead of requiring arrays to have identical dimensions, NumPy automatically "broadcasts" smaller arrays to match larger ones.

### Example 1: Adding a 1D array to a 2D matrix
This cell shows `A` (shape 2×2) + `b` (shape 2):
- `A` is `[[1,2], [3,4]]` (2×2 matrix)
- `b` is `[1, 2]` (1D array with 2 elements)
- NumPy broadcasts `b` to each row of `A`
- Equivalent to: `[[1,2], [3,4]] + [[1,2], [1,2]]`
- Result: `[[2,4], [4,6]]`

**Broadcasting rule applied**: The 1D array `b` is replicated along the missing dimension (rows) to match the 2D matrix shape.

In [49]:
A = np.array([[1, 2],
              [3, 4]])
b = np.array([1, 2])
print(A + b)

[[2 4]
 [4 6]]


### Example 2: Broadcasting with different dimension combinations
This cell shows `A` (shape 3×1) + `b` (shape 3):
- `A` is `[[1], [2], [3]]` (3×1 column vector)
- `b` is `[10, 20, 30]` (1×3 row vector)
- NumPy broadcasts both arrays to shape 3×3:
  - `A` is replicated horizontally across columns
  - `b` is replicated vertically down rows
- Equivalent to: `[[1,1,1], [2,2,2], [3,3,3]] + [[10,20,30], [10,20,30], [10,20,30]]`
- Result: `[[11,21,31], [12,22,32], [13,23,33]]`

**Key Broadcasting Rules**:
1. Arrays with fewer dimensions are padded with 1s on the left
2. Dimensions of size 1 are stretched to match the other array
3. If dimensions don't match and neither is 1, an error occurs

Broadcasting makes code more efficient and readable by eliminating the need for explicit loops or array replication.

In [50]:
A = np.array([[1],
              [2],
              [3]])
b = np.array([10, 20, 30])
print(A + b)

[[11 21 31]
 [12 22 32]
 [13 23 33]]
